#!/bin/bash

set -e

#Compile

diff -u <(echo -n) <(gofmt -s -d $(find . -type f -name '*.go' -not -path "./vendor/*"))
go test $(go list ./... | grep -v /vendor/)


platforms=("windows/amd64" "linux/amd64" "darwin/amd64")
for platform in "${platforms[@]}"
do
    platform_split=(${platform//\// })
    GOOS=${platform_split[0]}
    GOARCH=${platform_split[1]}
    echo "Building for " $GOOS "-" $GOARCH

    output_name=echo'-'$GOOS'-'$GOARCH
    if [ $GOOS = "windows" ]; then
        output_name+='.exe'
    fi

   
    rm -f $output_name
    env GOOS=$GOOS GOARCH=$GOARCH go build -o $output_name
done
